- name: RouterOS test with network_cli connection
  hosts: routers
  gather_facts: false
  
  vars:
     var_USER: "{{ lookup('env','USER') }}"
     id_rsa_pub_var: "{{ lookup('file', '/home/{{ var_USER }}/.ssh/id_rsa.pub') }}"    
  
  tasks:  
  - community.routeros.command:
      commands:
        - /file print file=id.rsa.pub; /file set "id.rsa.pub" contents="{{ id_rsa_pub_var }}"
    register: id_rsa_pub_var_set   
  
  - community.routeros.command:
      commands:
        - /user ssh-keys import user="{{ ansible_user }}" public-key-file=id.rsa.pub

  - community.routeros.command:
      commands:
        - /file remove id.rsa.pub
